### ISSUE TITLE
Any chance to replicate this for Python Flask

### ISSUE THREAD

**Issue by ccrvlh** [IntuitDeveloper/SampleApp-CRUD-PHP#3]
I'm having a hard time replicating the examples using Python Flask.

My main objectives are:
1. Create a Sales Receipt
2. Create Invoice
3. Receive payment (applied to specific invoice)

Not very much documentation and samples for developing with Python...

Thanks a lot!

**Comment by diana-derose** [comment]
Hi, Please refer to the sample below for Python Flask-
https://github.com/IntuitDeveloper/SampleApp-QuickBooksV3API-Python
It has the code for create customer but can be modified to create sales receipt or invoice as well.

**Comment by ccrvlh** [comment]
Thanks for you answer, the code makes sense and helps a lot, but from what I understand it still uses OAuth1, which doesn't work anymore, might be worth to update it so it can be a working sample.
Thanks!
