### ISSUE TITLE
Use of undefined constant OAUTH_SIG_METHOD_HMACSHA1

### ISSUE THREAD

**Issue by harshsanghani** [IntuitDeveloper/SampleApp-CRUD-PHP#4]
I got this issue when I try to fetch contact list.
![check](https://user-images.githubusercontent.com/15828332/35390221-9f6c5c4c-0200-11e8-83cc-ad3b3f6af833.png)

Use of undefined constant OAUTH_SIG_METHOD_HMACSHA1 - assumed 'OAUTH_SIG_METHOD_HMACSHA1' in E:\xampp\htdocs\demo\quick_book\v3-php-sdk-2.4.1\Security\OAuthRequestValidator.php on line 80

**Comment by hlu2** [comment]
@harshsanghani  the SDK has been updated.
